### ISSUE TITLE
Implement LoginController and Router to retrieve user token

### ISSUE THREAD

**Issue by DannyPeck** [CS450-ECE461/fall2016-group2-adminportal#3]
Create a LoginRouter and LoginController with a login method.  This login method will send a POST request to the route 'apiserver-ip-address/login' with the following request body:

```JavaScript
{
   "username": "username",
   "password":  "password"
}
```

In order for login to work you will need to have a user stored within the database, you can create a user in the apiserver database via sending a POST request to the test route 'apiserver-ip-address/dev/users'.  The request body will look as follows:

```JavaScript
{
   "user": {
	"username": "username",
	"password": "password",
	"email": "email",
	"job_title": "Software Engineer"
    }
}
```

The login route on the backend will validate the user credentials and generate an access_token for that user.  If the request fails, it should return a 404 for the user doesn't exist or a 400 if the request was bad (invalid token, invalid password).  If the route succeeds it will return a 200 OK and the access_token.

**Comment by eburgun** [comment]
Implemented and token retrieved.
